function [superblockProfiles,blockProfiles,nFGBlocks,res]=profilePR(tissueRegionList,prModel)

% A convenience wrapper around the rip_image function of PhenoRipper to enable profiling tissue image regions based on a trained PhenoRipper model.
%
% INPUTS
% tissueRegionList -	A struct containing a list of tissueRegions as defined by TissueRegionList_Generator.m 
% 			that we wish to profile
% prModel	   - 	A pretrained PhenoRipper model (as generated by TrainPR.m) which we wish to use to 
% 			perform profiling. Note: all phenoripper parameters will be inherited from this model.
%
% OUTPUT	   
% superBlockProfiles, blockProfiles,nFGBlocks are the superblock profiles, bnlock profiles, and number of foreground blocks 
% respectively for each tissueRegion
% results is a struct containing the results output by phenoripper, which contains additional profiling information
%
number_of_files=length(tissueRegionList);
blockProfiles=zeros(number_of_files,prModel.number_of_block_clusters);
superblockProfiles=zeros(number_of_files,prModel.number_of_superblocks);
nFGBlocks=zeros(number_of_files,1);



%Calculating Block Profiles for the full dataset (Image Ripping)


%timeSoFar=0;
res=cell(number_of_files,1);
nargs=nargout;
parfor file_num=1:number_of_files
    %tic;
    filenames_rescale_param={{1},{0}};
    results=rip_image(tissueRegionList(file_num),...
        prModel,...
        prModel.marker_scales,...
        prModel.include_bg,...
        prModel.foreground_channels,...
        prModel.analyze_channels,...
        filenames_rescale_param);
    
    blockProfiles(file_num,:)=results.block_profile;
    superblockProfiles(file_num,:)=results.superblock_profile;
    nFGBlocks(file_num)=results.number_of_foreground_blocks;
    %disp(['Finished ' num2str(file_num) '/' num2str(number_of_files)]);
    %elapsedTime=toc;
    %timeSoFar=timeSoFar+elapsedTime;
    %expectedTime=((number_of_files-file_num)*timeSoFar/file_num)/60;
    %disp(['Expected To Finish in ' num2str(expectedTime) ' minutes']);
    if(nargs>3)
        res{file_num}=results;
    end
end


end
