function prModel=TrainPR(trainingTissueRegionList,block_size,marker_scales,cutoff_intensity)

% A conveneince wrapper around PhenoRipper's functions to ease training on a set of tissue images.
% In  addition to generalizing the training to tissueImages, this function sets default values for
% a number of parameters, exposing a much smaller set to the user.
% INPUTS
% tissueRegionList -	A struct containing a list of tissueRegions as defined by TissueRegionList_Generator.m 
% 			that we wish to use to train PhenoRipper.
% blockSize        - 	Size in pixels of the blocks that PhenoRipper divides images into.
% marker_scales    -    A 2D matrix of size number_of_channels x 2 which denotes the min/max intensity scale for each channel.
% 			These numbers are used to scale marker intensities into the [1,100] range. Note:
% 			intensities outside these limits are saturated out.			
% cutoffIntensity  - 	A numeric value indicating the intensity on the [1,100] scale below which pixels are considered as background.
%
% OUTPUT	  
% prModel          -    A struct containing the model definition of the trainined PhenoRipper model that can be used to profile new images by profilePR.m 
number_of_RGB_clusters=10;
number_of_block_clusters=10;
number_of_superblocks=30;
number_of_blocks_per_training_image=1000;
rgb_samples_per_training_image=3000;
number_of_block_representatives=3;
include_bg=true;
foreground_channels=true(size(marker_scales,1),1);% needs changing
analyze_channels=true(size(marker_scales,1),1);% needs changing
trainingTissueRegionList_rescale_param=cell(length(trainingTissueRegionList),1);
c={1,0};
trainingTissueRegionList_rescale_param(:)={c};

prModel=identify_block_types(...
    trainingTissueRegionList,...
    block_size,...
    cutoff_intensity,...
    number_of_RGB_clusters,...
    number_of_block_clusters,...
    number_of_blocks_per_training_image,...
    rgb_samples_per_training_image,...
    number_of_block_representatives,...
    marker_scales,...
    include_bg,...
    foreground_channels,...
    analyze_channels,...
    trainingTissueRegionList_rescale_param);

sbModel=identify_superblock_types(...
    trainingTissueRegionList,...
    prModel,...
    number_of_superblocks,...
    marker_scales, include_bg,...
    foreground_channels,...
    analyze_channels,...
    trainingTissueRegionList_rescale_param);

prModel.superblock_centroids=sbModel.superblock_centroids;
prModel.superblock_representatives=sbModel.superblock_representatives;
prModel.number_of_superblocks=number_of_superblocks;
prModel.marker_scales=marker_scales;
prModel.include_bg=include_bg;
prModel.foreground_channels=foreground_channels;
prModel.analyze_channels=analyze_channels;
end
